stages:
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules

deploy:
  stage: deploy
  only:
    - master
  script:
    - curl -L http://collection.b0.upaiyun.com/softwares/upx/upx-linux-amd64-v0.2.3 -o upx
    - chmod a+x ./upx
    - ./upx login $UPYUN_BUCKET $UPYUN_USER $UPYUN_PASSWORD
    - cd dist; ../upx put ./ ./
