language: node_js
node_js: stable

cache:
  directories:
    - node_modules

script:
  - curl -L http://collection.b0.upaiyun.com/softwares/upx/upx-linux-amd64-v0.2.3 -o upx
  - chmod a+x ./upx
  - ./upx login $UPYUN_BUCKET $UPYUN_USER $UPYUN_PASSWORD
  - cd dist; ../upx put ./ ./

branches:
  only:
    - master
